### ISSUE TITLE
Don't see login with OpenStreetMap on Firefox

### ISSUE THREAD

**Issue by bkowshik** [osmlab/to-fix#212] opened 2017-07-03 11:43 UTC
## In Chrome

<img width="1227" alt="screen shot 2017-07-03 at 4 31 06 pm" src="https://user-images.githubusercontent.com/2899501/27790248-58d0f8e6-600d-11e7-82ca-846d0223be66.png">

## But, in Firefox
<img width="1227" alt="screen shot 2017-07-03 at 4 31 41 pm" src="https://user-images.githubusercontent.com/2899501/27790247-58cf5ea0-600d-11e7-86fc-c4152c5f753b.png">

---

cc: @amishas157

**Comment by 1ec5** [comment] 2017-07-07 04:11
The button is there, but only a tiny sliver of it is visible. It’s the purple line in the second screenshot.

**Comment by 1ec5** [comment] 2017-07-07 04:13
Duplicate of #197.

**Closed by 1ec5** 2017-07-07 04:13 UTC
